#ifndef __OLED_H__
#define __OLED_H__

#define OLED_DELAYS_HWFILL		(3)
#define OLED_DELAYS_HWLINE      (1)


#define OLED_CMD_DRAWLINE 		0x21
#define OLED_CMD_DRAWRECT 		0x22
#define OLED_CMD_CLEARWINDOW    0x25
#define OLED_CMD_FILL 			0x26
#define OLED_CMD_SETCOLUMN 		0x15
#define OLED_CMD_SETROW    		0x75
#define OLED_CMD_CONTRASTA 		0x81
#define OLED_CMD_CONTRASTB 		0x82
#define OLED_CMD_CONTRASTC		0x83
#define OLED_CMD_MASTERCURRENT 	0x87
#define OLED_CMD_SETREMAP 		0xA0
#define OLED_CMD_STARTLINE 		0xA1
#define OLED_CMD_DISPLAYOFFSET 	0xA2
#define OLED_CMD_NORMALDISPLAY 	0xA4
#define OLED_CMD_DISPLAYALLON  	0xA5
#define OLED_CMD_DISPLAYALLOFF 	0xA6
#define OLED_CMD_INVERTDISPLAY 	0xA7
#define OLED_CMD_SETMULTIPLEX  	0xA8
#define OLED_CMD_SETMASTER 		0xAD
#define OLED_CMD_DISPLAYOFF     0xAE
#define OLED_CMD_DISPLAYON     	0xAF
#define OLED_CMD_POWERMODE 		0xB0
#define OLED_CMD_PRECHARGE 		0xB1
#define OLED_CMD_CLOCKDIV 		0xB3
#define OLED_CMD_PRECHARGEA 	0x8A
#define OLED_CMD_PRECHARGEB 	0x8B
#define OLED_CMD_PRECHARGEC 	0x8C
#define OLED_CMD_PRECHARGELEVEL 0xBB
#define OLED_CMD_VCOMH 			0xBE

#endif
